### ISSUE TITLE
PIP version breaks

### ISSUE THREAD

**Issue by lethargilistic** [Dfenestrator/GooPyCharts#6]
The version on PIP breaks, currently.

[The line that used to import `_templates.py`](https://github.com/Dfenestrator/GooPyCharts/blob/master/gpcharts.py#L19) needs to be removed.

I'm just raising a new issue so you'll be sure to see this. I'll fix this after work, if you haven't.

**Comment by Dfenestrator** [comment]
And I thought I had it all tested too, ah well.

Thanks for letting me know. Don't worry about fixing it, I'll remove it and then upload it to pip. I should be able to get to this tonight.

**Comment by Dfenestrator** [comment]
Fixed
